# dataset dataloader
____

## 1. how shuffle works?
   > if shuffle is enabled in DataLoader function, it will randomly generate index based on the size and the batch_size

In [5]:
import torch
import torch.utils.data as data
torch.manual_seed(1)
class DemoDataset(data.Dataset):
    def __init__(self):
        super(DemoDataset,self).__init__()
    
    def __len__(self):
        return 11
    
    def __getitem__(self,idx):
        return idx

demo_dataset = DemoDataset()

In [7]:
# if we set batch_size to 1 and shuffle is disabled
demo_loader = data.DataLoader(demo_dataset,batch_size=1,shuffle=False, num_workers=0)

for i in iter(demo_loader):
    print(i)

tensor([0])
tensor([1])
tensor([2])
tensor([3])
tensor([4])
tensor([5])
tensor([6])
tensor([7])
tensor([8])
tensor([9])
tensor([10])


In [8]:
# if we set batch_size to 1 and shuffle is enabled
demo_loader = data.DataLoader(demo_dataset,batch_size=1,shuffle=True, num_workers=0)

for i in iter(demo_loader):
    print(i)

tensor([0])
tensor([2])
tensor([4])
tensor([7])
tensor([3])
tensor([8])
tensor([1])
tensor([6])
tensor([5])
tensor([9])
tensor([10])


In [10]:
# if we set batch_size to 2 and shuffle is enabled
demo_loader = data.DataLoader(demo_dataset,batch_size=2,shuffle=True, num_workers=0)

for i in iter(demo_loader):
    print(i)

tensor([ 0, 10])
tensor([7, 1])
tensor([2, 8])
tensor([9, 5])
tensor([3, 6])
tensor([4])


In [11]:
# if we set batch_size to 3 and shuffle is enabled
demo_loader = data.DataLoader(demo_dataset,batch_size=3,shuffle=True, num_workers=0)

for i in iter(demo_loader):
    print(i)

tensor([4, 1, 2])
tensor([6, 8, 7])
tensor([0, 5, 9])
tensor([10,  3])
